In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('/content/Data_for_UCI_named.csv')
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [ ]:
data.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [ ]:
data.drop('stab', axis=1, inplace=True)

In [ ]:
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [ ]:
data['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [ ]:
X = data.drop(columns='stabf')
y = data['stabf']

In [ ]:
 # Split the data into train and test sets

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=1)
y_train.value_counts()

unstable    5092
stable      2908
Name: stabf, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

normalised_xtrain = scaler.fit_transform(x_train) 
normalised_xtest = scaler.transform(x_test)

In [ ]:
# Random Forest

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix

model1 = RandomForestClassifier(random_state=1)
model1.fit(normalised_xtrain, y_train)
y_pred1 = model1.predict(normalised_xtest)

cnf_mat = confusion_matrix(y_true=y_test,y_pred=y_pred1, labels=['unstable', 'stable']), 
cnf_mat

(array([[1233,   55],
        [  87,  625]]),)

In [ ]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred1)
accuracy

0.929

In [ ]:
# ExtraTreesClassifier

from sklearn.ensemble import ExtraTreesClassifier

model2 = ExtraTreesClassifier(random_state=1, cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1)
model2.fit(normalised_xtrain, y_train)
y_pred2 = model2.predict(normalised_xtest)

cnf_mat = confusion_matrix(y_true=y_test,y_pred=y_pred2, labels=['unstable', 'stable']), 
cnf_mat

(array([[1250,   38],
        [ 106,  606]]),)

In [ ]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred2)
accuracy

0.928

In [ ]:
# XGBoost Classifier

from xgboost import XGBClassifier

model3 = XGBClassifier(random_state = 1)
model3.fit(normalised_xtrain, y_train)
y_pred3 = model3.predict(normalised_xtest)

cnf_mat = confusion_matrix(y_true=y_test,y_pred=y_pred3, labels=['unstable', 'stable']), 
cnf_mat

(array([[1236,   52],
        [ 109,  603]]),)

In [ ]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred3)
accuracy

0.9195

In [ ]:
# LGBM

from lightgbm import LGBMClassifier


model4 = LGBMClassifier(random_state=1)
model4.fit(normalised_xtrain, y_train)
y_pred4 = model4.predict(normalised_xtest)

cnf_mat = confusion_matrix(y_true=y_test,y_pred=y_pred4, labels=['unstable', 'stable']), 
cnf_mat

accuracy = accuracy_score(y_true=y_test, y_pred=y_pred4)
accuracy

0.9375

In [ ]:
#HyperTuning the ExtraTreesClassifier

n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 

from sklearn.model_selection import RandomizedSearchCV
grid = {'n_estimators': n_estimators,'min_samples_leaf': min_samples_leaf,'min_samples_split': min_samples_split,'max_features': max_features}

model=ExtraTreesClassifier()
rs_grid = RandomizedSearchCV(model, param_distributions = grid, cv=5, n_iter=10, n_jobs=-1, verbose=1, random_state=1, scoring='accuracy')
rs_grid.fit(normalised_xtrain, y_train)
rs_grid.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [ ]:
model_opt=ExtraTreesClassifier(max_features=None,min_samples_leaf=8,min_samples_split=2, n_estimators=1000)
model_opt.fit(normalised_xtrain, y_train)
y_pred=model_opt.predict(normalised_xtest)
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
accuracy

0.9285

The accuracy score of the optimal model is higher

In [ ]:
#Feature Importances

features = model_opt.feature_importances_
xyz=pd.DataFrame(features, index=Xt_S.columns, columns=['Importance'])
print("Max Importance is of: ", xyz[['Importance']].idxmax())
print("Min Importance is of: ", xyz[['Importance']].idxmin())

NameError: ignored